[2025-02-07T21:27:02.876+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T21:27:02.881+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_four_python_files.run_bronze scheduled__2025-02-07T12:26:00+00:00 [queued]>
[2025-02-07T21:27:02.884+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_four_python_files.run_bronze scheduled__2025-02-07T12:26:00+00:00 [queued]>
[2025-02-07T21:27:02.884+0900] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-07T21:27:02.889+0900] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_bronze> on 2025-02-07 12:26:00+00:00
[2025-02-07T21:27:02.896+0900] {logging_mixin.py:190} WARNING - /Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=27529) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-07T21:27:02.897+0900] {standard_task_runner.py:72} INFO - Started process 27534 to run task
[2025-02-07T21:27:02.895+0900] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'run_four_python_files', 'run_bronze', 'scheduled__2025-02-07T12:26:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/run_four_files.py', '--cfg-path', '/var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T/tmpdoihcqmi']
[2025-02-07T21:27:02.897+0900] {standard_task_runner.py:105} INFO - Job 11: Subtask run_bronze
[2025-02-07T21:27:02.916+0900] {task_command.py:467} INFO - Running <TaskInstance: run_four_python_files.run_bronze scheduled__2025-02-07T12:26:00+00:00 [running]> on host macbook-pro-3.local
[2025-02-07T21:27:02.948+0900] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_four_python_files' AIRFLOW_CTX_TASK_ID='run_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T12:26:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-07T12:26:00+00:00'
[2025-02-07T21:27:02.949+0900] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T21:27:02.960+0900] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T
[2025-02-07T21:27:02.960+0900] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'python ../../bronze/raw_data2.py']
[2025-02-07T21:27:02.964+0900] {subprocess.py:99} INFO - Output:
[2025-02-07T21:27:02.977+0900] {subprocess.py:106} INFO - python: can't open file '/private/var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T/airflowtmpjso2sw7_/../../bronze/raw_data2.py': [Errno 2] No such file or directory
[2025-02-07T21:27:02.979+0900] {subprocess.py:110} INFO - Command exited with return code 2
[2025-02-07T21:27:02.983+0900] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-02-07T21:27:02.987+0900] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=run_four_python_files, task_id=run_bronze, run_id=scheduled__2025-02-07T12:26:00+00:00, execution_date=20250207T122600, start_date=20250207T122702, end_date=20250207T122702
[2025-02-07T21:27:02.992+0900] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T21:27:02.992+0900] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task run_bronze (Bash command failed. The command returned a non-zero exit code 2.; 27534)
Traceback (most recent call last):
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-02-07T21:27:03.004+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-07T21:27:03.013+0900] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-07T21:27:03.014+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
